### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ParsifalC**
- 中英文排版问题
- 错别字
- 部分翻译问题
- 代码格式

### CODE REVIEW

**Comment by faisalmemon** [comment]
I've noticed you've made the markdown verbose sections language specific such as:
three back-ticks and then objectivec (```objectivec)

I just need to check my markdown_fold program still works with this (it automatically wraps long lines for the print version of the book).  I also need to port that enhancement back to the English version.

I won't be able to do this work until later on in the week.

In the meantime, thank you for the update proposal; I really appreciate the collaboration from you on this.

**Comment by ParsifalC** [comment]
> I've noticed you've made the markdown verbose sections language specific such as:
> three back-ticks and then objectivec (```objectivec)
> 
> I just need to check my markdown_fold program still works with this (it automatically wraps long lines for the print version of the book). I also need to port that enhancement back to the English version.
> 
> I won't be able to do this work until later on in the week.
> 
> In the meantime, thank you for the update proposal; I really appreciate the collaboration from you on this.

yeah,u can try (\```oc)  or (\```objective-c) if (\```objectivec) not works.it just depends on different MarkDown renders.it's easier to read with these highlights.

**Comment by ParsifalC** [comment]
> * 中英文排版问题
> * 错别字
> * 部分翻译问题
> * 代码格式

@LoneyIsError thanks for the review of Chinese part.

**Comment by LoneyIsError** [comment]
@ParsifalC Strive to make the translated content more accurate. I will proofread it every once in a while. I hope that more people can participate and make the Chinese version more perfect.

**Comment by LoneyIsError** [comment]
@ParsifalC If you want, you can communicate with me on WeChat

**Pull request merged**
