### PR TITLE
Fix typo: 奔溃 -> 崩溃

### PR DESCRIPTION
**Pull request by leilee**

### CODE REVIEW

**Comment by faisalmemon** [comment]
I've asked my Chinese language translator to review this change.  I can see that you have improved the phrasing of the sentences but I am not knowledgeable about Chinese.  If there are no follow ups or further suggestions from @LoneyIsError after one week, I will just merge in the updates.

I am grateful for your contribution to the text, and I hope to get back to you soon afterwards.  Thank you very much.

**Comment by faisalmemon** [comment]
I've locally built the changes, and the html version of the book builds ok.

**Comment by LoneyIsError** [comment]
Thank you for your proofreading, I will be more careful, this is caused by carelessness in translation. Sorry for such a problem.

**Comment by faisalmemon** [comment]
Thanks for your input @LoneyIsError No problem, we are all just working together to get the best outcome with our collective skills and knowledge.  I will merge in the changes.

**Pull request merged**
